# Generated by Django 4.1.2 on 2023-09-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(default='', upload_to='media/images')),
                ('liveproject', models.URLField(max_length=500)),
                ('code', models.URLField(max_length=500)),
            ],
        ),
    ]
