# Generated by Django 4.1.2 on 2024-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.IntegerField(blank=True)),
            ],
        ),
    ]
